name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: abhishekdubey-git/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
      
      - name: Calling chat gpt api for code review
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.openai.com/v1/chat/completions'
        method: 'POST'
        bearerToken: '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'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{
"model":"gpt-3.5-turbo","temperature":0.2,"max_tokens":700,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"messages":[{"role":"system","content":"Your task is to review pull requests. Instructions:\\n- Provide the response in following JSON format:  [{\\"lineNumber\\":  <line_number>, \\"reviewComment\\": \\"<review comment>\\"}]\\n- Do not give positive comments or compliments.\\n- Provide comments and suggestions ONLY if there is something to improve, otherwise return an empty array.\\n- Write the comment in GitHub Markdown format.\\n- Use the given description only for the overall context and only comment the code.\\n- IMPORTANT: NEVER suggest adding comments to the code.\\n\\nReview the following code diff in the file \\".github/workflows/main.yml\\" and take the pull request title and description into account when writing the response.\\n  \\nPull request title: added get users api\\nGit diff to review:\\n\\n```  @RestController
public class UserController {

	@GetMapping("/users")
	public List getUsers() {
		return List.of("user1", "user2", "user3", "user4");
	}

} \\n```\\n"}
		]
}'
