name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Calling chat gpt api for code review
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.openai.com/v1/chat/completions'
          method: 'POST'
          bearerToken: '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'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"model":"gpt-3.5-turbo","temperature":0.2,"max_tokens":700,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"messages":[{"role":"system","content":"Can you please do a code review for me?"}]}'
